### ISSUE TITLE
Allow Presets To Be Updated Automatically

### ISSUE THREAD

**Issue by thommcgrath** [thommcgrath/Beacon#10]
Using the same classes.php file (I knew I should have renamed that) include updated presets. App will need to start keeping the built-in presets in App Support. Included presets would get copied in.

Or maybe they get stored in the database...

**Comment by JamieKG** [comment]
by this do you mean when you edit a preset it will be update wherever you have used it in your item sets ?

**Comment by thommcgrath** [comment]
No. I mean adding/changing/removing built-in presets according to the server. It helps me make builds less frequently. I do not want to be automatically tampering with the defined loot. That will always require user intervention.
