### ISSUE TITLE
[Feature Request] Edit presets independent of loot source

### ISSUE THREAD

**Issue by jrobinson3k1** [thommcgrath/Beacon#100]
I don't see a way to edit an item set outside it's loot source. I have an issue where I want to make sweeping changes to an item set and resync those changes to all the loot sources that use it, but the only way I can see to edit an item set is to edit it from inside a loot source. There is an independent New Preset option, but not Edit Preset.

The issue with editing a preset from within a loot source is that it populates the item set with the modifiers for the loot source. For example, I have a Guns preset that has Assault Rifle that can spawn 1-1 items with Primitive to Journeyman. If I edit the Guns item set inside an Island Red Bonus loot source, which has 2x items and +3 item quality, it will show the Assault Rifle as 2-2 items with Apprentice to Ascendant. If I change nothing and save to library, then rebuild the item set, it now will show 4-4 items with Epic to Pearlescent. The only way to truly edit the base values of a preset is to edit from a loot source that has no modifiers.

**Comment by thommcgrath** [comment]
Everything you're looking for should be in the Presets of the Library. You can access it by choosing "Library" from the "Window" menu. There you can create, edit, and delete presets.

**Comment by jrobinson3k1** [comment]
I was hoping it was something I was overlooking @thommcgrath . Thanks.
