### ISSUE TITLE
Aberration Loot Levels 

### ISSUE THREAD

**Issue by PVPEllie** [thommcgrath/Beacon#109]
Hi, i'm trying to create custom drops, but the survivor level is set to:
White = Level 3
Green = Level 15
Blue = Level 25
Purple = Level 35
Yellow = Level 45
Red = Level 60

However, the default set by WildCard is that drops are the following:

White = Level 10
Green = Level 25
Blue = Level 35
Purple = Level 50
Yellow = Level 65
Red = Level 80

Because of this i can't use any drops i create as the "supply crate" is incorrect, and when changed manually to the correct levels it doesn't work. Any advice?

**Comment by thommcgrath** [comment]
Make sure you're using the correct drops. Can you tell me one of the SupplyCrateClassString values you're seeing?

I have a feeling you have your map set to The Island in Beacon, so Beacon will show you drops for The Island. Aberration using different drops. So I would click the gear icon in the lower right of the loot sources list, add Aberration but do not remove The Island yet. Select each of your crates you setup for The Island, and choose "Document -> Duplicate Loot Source" from the menubar. You'll want to duplicate your Island drops into Aberration drops. After you've done that, you can click the gear icon again and remove The Island as a selected map. The Island drops will remain, but that's ok, Beacon won't export them. You can delete them if you wish.
