### ISSUE TITLE
Show BP% on main screen

### ISSUE THREAD

**Issue by tommy290** [thommcgrath/Beacon#11]
It would make it easier to see how you have blueprints configured if you could see the percent chance on the same screen as everything else. Maybe just a column after the % chance?

**Comment by thommcgrath** [comment]
Definitely feels missing doesn't it? I've been meaning to handle this, just haven't yet.

**Comment by thommcgrath** [comment]
Fixed with https://github.com/thommcgrath/Beacon/commit/4c440046fc3864582b92d04376523119b81bc6c1
