### ISSUE TITLE
Beacon does not know the blueprint for....

### ISSUE THREAD

**Issue by malosaa** [thommcgrath/Beacon#110]
SO i added manually some of the items to the drops and they work.. but are not in the list from beacon. like all the berry speedhacks, and structure turret plant,Berrysoup primal item, and craftable primal item...

There are more items what are not added to the game..

please add them as i still need to add them manual all the time and cant save them with beacon, it shows up red for me 

regards

**Comment by thommcgrath** [comment]
Sorry for taking so long to reply. Can you point me to specific items that are missing?

You can also manage your own engrams using the drawer on the left. Beacon will remember them as if they are built-in.
