### ISSUE TITLE
Option to make your Game.ini public

### ISSUE THREAD

**Issue by dominikprot** [thommcgrath/Beacon#127]
Hi,

so what I found is that many server owners want similar things in their supply drops.
Wouldn't it be cool to be able to see what others are doing and if the Game.ini I want probably already exists?
The usability of the tool is great, but if I want to highly customize the drops it still takes a lot of effort, so this would be a nice touch.

**Comment by thommcgrath** [comment]
That is exactly what the community document browser inside Beacon and at https://beaconapp.cc/browse/ does.

**Comment by dominikprot** [comment]
Wow im blind, thanks a lot.
