### ISSUE TITLE
Parse error trying to import a server for the first time

### ISSUE THREAD

**Issue by JakeSkully** [thommcgrath/Beacon#128]
I have just installed Beacon on my Win 10 system.
I am trying to get the import from a Nitrado server as my "Select Import Source".  I have the server set to expert mode and the only change I made manually to the "GameUserSettings.ini" is to add "[StructuresPlus]
NoFoundationsRequired=true" to the end of the file.  The server starts and is running

I can see my server and select it and try to import.
The message shows it getting "Game.ini" then moving to "GameUserSettings.ini" for a few seconds then I get a message "No files imported" Beacon was not able to import anything from the selected files" and under the server name in the "Import Status" UI it shows "Parse error"

**Comment by thommcgrath** [comment]
First, confirm that you’re using Beacon 1.0.1, as that fixes a false parse error on Windows.

If you are, then there is likely something wrong with one of the files that is giving Beacon trouble.

**Comment by JakeSkully** [comment]
I am using 1.0.1.  I downloaded it today and installed it.
I have tried putting the server back to simple configuration and that gives the error also.
Is there a log file somewhere that might give me a clue as to the issue?

**Comment by JakeSkully** [comment]
I downloaded both files and tried manually importing them and the one that gives an error is the "Game.ini" file.
Here are the contents.  To my knowledge I did not make any changes to this file but it is possible I made an unintended change.  Here is the contents of that file.

[/script/shootergame.shootergamemode]
bOnlyAllowSpecifiedEngrams=false
GlobalSpoilingTimeMultiplier=0
GlobalItemDecompositionTimeMultiplier=0
GlobalCorpseDecompositionTimeMultiplier=0
PvPZoneStructureDamageMultiplier=6.0
bPvEDisableFriendlyFire=false
ResourceNoReplenishRadiusPlayers=1
ResourceNoReplenishRadiusStructures=1
bAutoPvETimer=false
bAutoPvEUseSystemTime=true
AutoPvEStartTimeSeconds=0
AutoPvEStopTimeSeconds=0
LayEggIntervalMultiplier=1.0
DinoTurretDamageMultiplier=1.0
bDisableLootCrates=false
DinoHarvestingDamageMultiplier=3.0
bDisableFriendlyFire=true
CustomRecipeEffectivenessMultiplier=1.0
CustomRecipeSkillMultiplier=1.0
MatingIntervalMultiplier=1.0
EggHatchSpeedMultiplier=1.0
BabyMatureSpeedMultiplier=1.0
bPassiveDefensesDamageRiderlessDinos=false
KillXPMultiplier=1.0
HarvestXPMultiplier=1.0
CraftXPMultiplier=1.0
GenericXPMultiplier=1.0
SpecialXPMultiplier=1.0
PGMapName=PGMap
PGTerrainPropertiesString=
bDisableDinoRiding=false
bDisableDinoTaming=false
bUseCorpseLocator=true
bDisableStructurePlacementCollision=false
FastDecayInterval=43200
bUseSingleplayerSettings=true
bAllowUnlimitedRespecs=false
SupplyCrateLootQualityMultiplier=1.0
FishingLootQualityMultiplier=1.0
BabyCuddleIntervalMultiplier=1.0
BabyCuddleGracePeriodMultiplier=1.0
BabyCuddleLoseImprintQualitySpeedMultiplier=1.0
BabyImprintingStatScaleMultiplier=1.0
PlayerHarvestingDamageMultiplier=1.0
CropGrowthSpeedMultiplier=1.0
BabyFoodConsumptionSpeedMultiplier=1.0
bPvEAllowTribeWar=true
bPvEAllowTribeWarCancel=false
CropDecaySpeedMultiplier=1.0
HairGrowthSpeedMultiplier=1.0
FuelConsumptionIntervalMultiplier=1.313000
KickIdlePlayersPeriod=3600
MaxNumberOfPlayersInTribe=0

**Comment by thommcgrath** [comment]
Thanks, I’ll see what the debugger is complaining about ASAP. I don’t see anything obviously wrong, so it’s probably a bug.

**Comment by thommcgrath** [comment]
Unfortunately, I've tried with 1.0.1 on both my Mac and Windows computers and both parse that content correctly. I'm not really sure what to advise at this point. This feels exactly like the bug that was fixed in 1.0.1 though, so I would just double check on Beacon's launch screen that it says "Version 1.0.1" below the "New Beacon File" and "Open Beacon File" buttons. It should be correct if you downloaded from Beacon's website today, but I don't know what else to recommend.

**Comment by JakeSkully** [comment]
Thank you for checking.  It must be a user error of some kind I just have no idea what it might be.  I will try and reinstall maybe that will be the magic :)

Here is a screenshot of the error and my Beacon home page when I launch the app.
![beaconerrormeassage](https://user-images.githubusercontent.com/39133591/50567999-18544f00-0d1a-11e9-95f6-cc9a9ed06cc4.png)
 
![beaconversionscreenshot](https://user-images.githubusercontent.com/39133591/50567975-9c5a0700-0d19-11e9-87eb-e1ad0170f222.png)
