### ISSUE TITLE
[QOL Feature Request] re-arrange order

### ISSUE THREAD

**Issue by JamieKG** [thommcgrath/Beacon#13]
not a important thing but would be nice to be able to move the Beacons and Item sets order

**Comment by thommcgrath** [comment]
Ha, you're right. I hadn't realized this was something I wanted myself.

**Comment by thommcgrath** [comment]
Do you think sorting alphabetically would be enough? For me personally, I've avoided adding item sets out of order to make sure they sort the same between two similar loot sources. Sorting alphabetically would solve my particular problem, but I'd like more input.

**Comment by JamieKG** [comment]
for me Item sets would be fine that way but i like to set my Beacons as follows 
but thats just my liking at the moment I just reorder in the exported ini file then re import them
![Order](http://i.imgur.com/o4naEnr.png)

**Comment by thommcgrath** [comment]
Ok. I've been working on some very significant changes that may naturally solve your source sorting issue.

**Comment by thommcgrath** [comment]
With the latest build, does this satisfy the spirit of your request?

**Comment by JamieKG** [comment]
yes sir it does thank you for this excellent time saving tool
