### ISSUE TITLE
Quantities reverting to 1

### ISSUE THREAD

**Issue by TheApok** [thommcgrath/Beacon#136]
Program was working great, then yesterday I decided to update some of my presets, now every time I make a new preset or edit an old preset and update it all items revert back to quantity of 1. I've uninstalled/reinstalled, unchecked boxes and rechecked boxes, nothing seem to work. My Server was scheduled to launch tonight, any assistance would be great! More frustrating is, if i go to view, then presets, it shows all my preset as they should be but if I try using one it changes quantities to 1

**Comment by thommcgrath** [comment]
What do you have for your quantity multipliers? Those are probably to blame.

**Comment by TheApok** [comment]
it is I had set them to 0 for quality and quantity because I was hoping for Apprentice - Mastercraft only, was trying to avoid Ascendant drops. I fixed the quantity multipliers they are now 1 but left the quality at 0. Will that affect anything?

**Comment by thommcgrath** [comment]
That's fine, it essentially means no changes.
