### ISSUE TITLE
Nitrado Login Empty

### ISSUE THREAD

**Issue by thommcgrath** [thommcgrath/Beacon#140]
I love the idea of this app.  thank you for your contribution to the community.  i am hoping that this login issue is handled as i would love to use the app.

i just downloaded the app.  i installed it without issue.  i watched your tutorial.  i then go to do an import of the config from nitrado.  i click the import button, the app launches a progress bar window and then a browser window in front of that.  on your video, this browser window loads a nitrado login.  in my experience, it has an empty window with only the title of the window filled in with "Browser".  there is no content.

have a great day and hope to hear from you.

_Originally posted by @mrlogun2 in https://github.com/thommcgrath/Beacon/issues/138#issuecomment-462087715_

**Comment by thommcgrath** [comment]
I would check antivirus/malware protection. It's just a simple web view, so the best I can guess is something is blocking the web request.

**Comment by mrlogun2** [comment]
this is a user side issue and not a bug in the app.  as you mentioned, i checked my antivirus/malware app and the subscription had ran out.  after fixing that and running things again, i was able to connect without issue.  thanks.

**Comment by thommcgrath** [comment]
Thanks for the update and good to hear it’s working for you now.
