### ISSUE TITLE
[Feature Request] double click an item for "Edit the selected items" 

### ISSUE THREAD

**Issue by RonCraig** [thommcgrath/Beacon#15]
Nice to have: Double click item to open "Edit the selected item" (aka Set Entry) form.

**Comment by RonCraig** [comment]
very nice! thanks.

**Comment by akmaslov** [comment]
This doesn't seem to be working on the Mac version.

**Comment by thommcgrath** [comment]
@akmaslov I cannot reproduce the problem on my Mac.

**Comment by akmaslov** [comment]
Hmmm, doesn't work for me on the PC either; I have to use the edit button for everything. That would generally point to user error, but double-click is a pretty simple gesture. 

Is your instance build from source, or installed?

**Comment by thommcgrath** [comment]
Oh wow, you are right. I thought I had made a build since then. It looks like the "build 8" I have in my Applications folder is not the same as the build 8 released. I'll get a new build out soon.
