### ISSUE TITLE
The Item i used for currency on my servers isnt working

### ISSUE THREAD

**Issue by Monkeys9115** [thommcgrath/Beacon#154]
The item Seed_Test (BerryBush Seeds) has been removed from beacon but i used that on my ps4 servers for currency and can no longer update drops without removing currency from my servers. Can you please add them back into beacon as a lot of people use this item as currency in servers

**Comment by thommcgrath** [comment]
BushBerry Seeds are a cheat item, so they have never been part of Beacon’s built in database. You can add them to your own library using the instructions in https://beaconapp.cc/read/5b5b15bf-6540-44cd-8a7c-5ad34e92eeba

**Comment by Monkeys9115** [comment]
I have done that but im getting error message saying it is unsafe for console

**Comment by thommcgrath** [comment]
Ok. I’m putting a build out tomorrow, I’ll have that fixed then.

**Comment by Monkeys9115** [comment]
never mind i just fixed it by turning of by turning of show only console safe engrams you first idea worked after all thank you so much for you help
