### ISSUE TITLE
Blueprint issues

### ISSUE THREAD

**Issue by DarkC0wb0y** [thommcgrath/Beacon#162]
I found a blueprint error for the structures plus industrial cooker, grill, and forge. Even pasting the spawn command for these items it comes back with no issues resolved. I have tried a couple different variations of the code to see if it would accept it but still no good. what do you recommend? I have also tried to attach a screen shot but it keeps throwing an error.

**Comment by thommcgrath** [comment]
Beacon knows the blueprint paths for those items already though. Can you share your Beacon file? If you're importing from a Game.ini file, I bet your class strings are wrong in the first place.

**Comment by DarkC0wb0y** [comment]
It is saying those items are not safe for "console" yet those are the ones on the engram list

**Comment by DarkC0wb0y** [comment]
![image](https://user-images.githubusercontent.com/48559205/54388934-f3128400-466c-11e9-8466-6ef0492769ca.png)

**Comment by thommcgrath** [comment]
Ok well that's different from a blueprint error. If you're deploying to a console server, you'll need to remove them. Beacon is right, they aren't safe for consoles. If you're not deploying to a console server, head to Document Properties and turn off "Show only console-safe Engrams."

<img width="342" alt="Screen Shot 2019-03-14 at 4 23 03 PM" src="https://user-images.githubusercontent.com/12851521/54388996-7637d800-4675-11e9-9db3-6d060de81f70.png">

**Comment by DarkC0wb0y** [comment]
ok I'll try that

**Comment by DarkC0wb0y** [comment]
I don't remember checking that box but that solved that issue. Thanks for the help

**Comment by thommcgrath** [comment]
Beacon checked it automatically during import if you imported from a console server. It would have thrown a notification in the notifications pane when it did it.
