### ISSUE TITLE
being removed from tribe after a server restart

### ISSUE THREAD

**Issue by gavriellastarr** [thommcgrath/Beacon#165]
i'm on a nitrado xbox server. on 3/14/19 i did a reinstall, added all my other config stuff and then decided to try beacon again and it's way better than it used to be and does a lot more that's really handy. after i set up everything, i used the deploy button and the restart within the tool. everything was good until i decided to change something, made the changes, and restarted the server. my character was still alive and the wyvern i had spawned in was still alive, but i was no longer the owner and i was no longer in a tribe. thinking it's just a glitch, i continued playing, this time in creative mode, spawning in 2 wyverns and starting some building. my server did it's scheduled restart, and when i logged back in, i was still alive, the wyverns were still alive, but i was once again not in a tribe and did not own the wyverns or what i had built.
today, 3/15/19, i reinstalled the server since i had no idea where the problem was. i changed all the config items to a similar set up as yesterday, added some more things in beacon and deployed the beacon changes and, i believe, restarted the server from within beacon. i logged in, forcetamed a couple dilos, created my tribe, then logged out and restarted the server. and the same thing happened. i was still alive, dilos were still alive, but i didn't own them and i was not i a tribe. 
i shut the server down and looked at the coding and everything looked ok. most of it is copy paste or from beacon deployment. the only bit of code that was unfamiliar to me was the 3 or 4 lines that are the beacon managed buttons, i think. so i deleted them, without making any other changes. i saved and restarted and i was still in my tribe and still owned my dinos. i logged out, left the server running and about a 30 mins later logged back in and things were still as they should be.
- i wait between 5 to 10  mins after making my final changes to restart the server
- the copy paste config is adding extinction and aberration dinos and removing some base game dinos
- the first 2 bad restarts, i know i played more than 15 mins, so a save should have happened
it seems really weird that removing those 3 or 4 lines should have made the difference, but it did, so i don't know if it's just ark being ark or something not playing well with other things.

**Comment by thommcgrath** [comment]
There’s no ini change that could be made that would do such a thing. But let’s see what we can do to figure it out.

In Beacon, when you go to your server list, you can right-click a server to reveal your backer up ini files. Beacon makes a backup of each file before doing the deploy.

What we need to do is compare the backed up version to the code on Nitrado after the restart. Maybe something will stand out as a problem.

However, this build of Ark has been very buggy. It’s possible this is nothing to do with Beacon. But I’d like to be sure.

**Comment by thommcgrath** [comment]
I received some ini content that I assume is related to this case. I think it's from the backup. I'd have to also see what Beacon put on Nitrado to compare, but I don't think this is something caused by Beacon. We've been hearing about users being removed from tribes a lot recently. Though the reproducibility of your case is definitely a curiosity.

**Comment by gavriellastarr** [comment]
yes, it is the ini from the beacon back up. i didn't thnk it was related to beacon either and it might not be, but it was weird that removing the 3 or 4 lines that were specific to beacon fixed it. i did a search for people being removed from their tribes, but didn't really see anything quite like what i was experiencing. i'll email the current nitrado inis, which are functioning properly. i'm willing to do another deployment from beacon to see if i can reproduce the issue, if it would help.

**Comment by thommcgrath** [comment]
Yeah, what I most want to see is your ini files before you do a deployment and after you do a deployment. And of course wether or not the `[Beacon]` group is to blame. I don't have an Xbox to test with myself. If the issue happens again after deployment, please remove the `Version=1.1.3` line first and try. I'm curious if it's the `Version` or `ManagedKeys` lines to blame. Or both.

**Comment by gavriellastarr** [comment]
i did another deployment and then made some loot crate changes in beacon. both times i had no issues after the server restart. it's probably ark being ark. if i make further changes with beacon and it starts removing from the tribe again, i'll shoot you an email with the inis. thanks for the quick responses!

**Comment by thommcgrath** [comment]
Thanks for the update!
