### ISSUE TITLE
Missing Item (plant turret)

### ISSUE THREAD

**Issue by kylerumpza** [thommcgrath/Beacon#166]
Hi, I had an item in my drops. it is cheat gfi plant 1 0 0, and it would spawn a plant species that doesnt need a crop plot or anything and places like an auto turret. they are no longer in my drops. Help!! thanks -kyle

**Comment by thommcgrath** [comment]
Beacon never removes anything without the user doing something. What exactly is happening? Does Beacon give you some kind of error?

**Comment by kylerumpza** [comment]
hey thomas. No, many servers have this in drops... In game, to spawn, it is cheat gfi Plant 1 0 0 .  I found ONE blueprint pathway of it online, and when i go to add it to my engrams in my beacon i import from clipboard and it says no engram entered

**Comment by thommcgrath** [comment]
I know the item, I'm just trying to figure out what exactly is happening. Is the red caution icon in Beacon lit up?

What if you try it like this, importing from the Wiki URL?
<img width="1307" alt="Screen Shot 2019-03-16 at 12 48 26 AM" src="https://user-images.githubusercontent.com/12851521/54470826-424bd800-4785-11e9-91a1-1d574c8429fd.png">

That should add it. Or it might tell you the item was skipped because it's already in your database.

**Comment by kylerumpza** [comment]
Well, you see, im going to confuse you here haha. Alot of big servers, if you are familiar with them, (Abnormal, Unreal, etc.) have these things that spawn in drops. Not plant species X. It is a plant species, but does not require a crop plot or anything. You place it just like you do an auto turret, doesnt need fertilizer, etc. .. I am trying to see if you or anyone on this forum knows. Only the biggest, most popular servers have them and wont give up their secret for it. All i know, to spawn it into the game, it is cheat gfi Plant 1 0 0. Also, ONE link i have found on the internet shows this pathway cheat giveitem 
"Blueprint'/Game/PrimalEarth/CoreBlueprints/items/Structures/Misc/PrimalItemStructure_TurretPlant.PrimalItemStructure_TurretPlant'" 1 1 0

**Comment by thommcgrath** [comment]
It's not confusing. That blueprint path you posted here is exactly the one on the wiki.

**Comment by kylerumpza** [comment]
i'm stupid. Got it haha. thanks man i was confused with something.

**Comment by thommcgrath** [comment]
Glad to hear you got it figured out.
