### ISSUE TITLE
admin command issue

### ISSUE THREAD

**Issue by Tandy069** [thommcgrath/Beacon#170]
hey, 
started a nitrado server yesterday and everything was fine till i added drop codes and now i cant access admin commands!!! nitrado said that its not an issue with them so can you please help ASAP

**Comment by thommcgrath** [comment]
Which platform?

**Comment by Tandy069** [comment]
ps4

**Comment by Tandy069** [comment]
PS4

Sent from my iPhone

On 5 Apr 2019, at 9:40 am, Thom McGrath <notifications@github.com<mailto:notifications@github.com>> wrote:


Which platform?

**Comment by thommcgrath** [comment]
So a quick Google search tells me that PS4 has no admin whitelisting feature. How have you been accessing the commands before?

**Comment by Tandy069** [comment]
L1 L2 SQUAR TRIANGLE allows you to use admin commands but after putting in scorched drops its taken away this option

**Comment by thommcgrath** [comment]
Hang tight, I’ve asked my Discord group for help because I’m just not familiar enough with using admin commands on PS4.

**Comment by thommcgrath** [comment]
A few users have reported the ServerAdminPassword config missing from GameUserSettings.ini. Check to make sure it’s still there. I don’t yet know why the line is being removed.

**Comment by Tandy069** [comment]
if the config is missing what do i type in to make it work again?

**Comment by thommcgrath** [comment]
Under the [ServerSettings] section, look for or add `ServerAdminPassword=<whatever password you want>`. The full config guide can be found at https://ark.gamepedia.com/Server_Configuration

**Comment by Tandy069** [comment]
that worked thank you very much.

**Comment by thommcgrath** [comment]
Thanks for confirming. I guess I have a bug to hunt down.
