### ISSUE TITLE
Beacon deploying incorrectly

### ISSUE THREAD

**Issue by USAFWMANN** [thommcgrath/Beacon#173]
throws ini codes like new drops into the middle of all the base codes and reverting them back to there default settings, beacon is setting us back further than helping us out.

**Comment by thommcgrath** [comment]
I’m going to need more details. Can you send me the Game.ini that you’re trying to deploy to, as well as your Beacon file? If you don’t want to attach them here, send them to forgotmyparachute@beaconapp.cc
