### ISSUE TITLE
I cant deploy!

### ISSUE THREAD

**Issue by zGNGeTLeFt** [thommcgrath/Beacon#181]
Hey, I can not press Deploy and upload it to my FTP server! Can anybody help me further? Quick answer would be great! My server was supposed to be online today!
![Screenshot_1](https://user-images.githubusercontent.com/50626763/57703895-34211780-7661-11e9-99ae-36f9a4fb2c19.png)

**Comment by thommcgrath** [comment]
See https://beaconapp.cc/help/updating_your_server_with_ftp for instructions. You’ll need to link your server first, so follow https://beaconapp.cc/help/importing_existing_config and at the post-import screen, choose only your “Server Link” line so you don’t overwrite any of your changes.

**Comment by zGNGeTLeFt** [comment]
If I click on Import I will come to my folder!
![Screenshot_3](https://user-images.githubusercontent.com/50626763/57705417-26b95c80-7664-11e9-9b8c-882d059dd70b.png)
![Screenshot_4](https://user-images.githubusercontent.com/50626763/57705422-291bb680-7664-11e9-8c95-e24a099d3b13.png)

**Comment by zGNGeTLeFt** [comment]
ohhh i found it thanks for help! <3 I found it over the YT channel Beacon

**Comment by thommcgrath** [comment]
Good, it sounds like you needed the “Enable Cloud & Community” link in the left menu.

**Comment by zGNGeTLeFt** [comment]
Still can not upload it! The rocket is still not clickable

**Comment by zGNGeTLeFt** [comment]
http://prntscr.com/noh4c3

**Comment by thommcgrath** [comment]
Who is your host? It’s possible their FTP server doesn’t support the MSLD command, which Beacon needs.

**Comment by zGNGeTLeFt** [comment]
Gportal is my host

**Comment by thommcgrath** [comment]
Ok. I’ll investigate their FTP. In the meantime, follow the manual instructions: https://beaconapp.cc/help/updating_your_server_manually

**Comment by zGNGeTLeFt** [comment]
I just did everything

**Comment by thommcgrath** [comment]
Do me a favor and try the FTP import again. There's a good chance it will still fail, but I've setup my server to send me debug output that I can use to improve support.
