### ISSUE TITLE
Stacking mod is not working

### ISSUE THREAD

**Issue by Ballsdeepemporer** [thommcgrath/Beacon#184]
when using deploy the stacking mod code isnt being added

**Comment by thommcgrath** [comment]
I’m sorry, but without any details, all I can do is guess. Stack size editing is a paid feature, so make sure you’re an owner of Beacon Omni. Beacon will allow you to try out the stack size editor for free, but won’t generate the ini lines for it until Omni is purchased.

If that isn’t the issue, try starting with https://beaconapp.cc/help/how_to_change_stack_sizes for more information about stack sizes. There are links in the table of contents about deploying and activating Omni too. Perhaps something there will help.
