### ISSUE TITLE
Game Ini files

### ISSUE THREAD

**Issue by arkmodderalex** [thommcgrath/Beacon#189]
I wanted to add the species X turret plants that when you type cheat gfi plant it spawns them without the  crop plant and they look like auto turrets in your inventory. Do you know the game ini file to add to my drops? also need help with rag desert drops. Please and thanks

**Comment by thommcgrath** [comment]
I'm sorry, I don't know the code you're looking for, but if you find it you can use the technique described in https://beaconapp.cc/help/adding_unsupported_engrams_to to add it to Beacon and put it in your drops. The Ragnarok desert drops use the "Scorched Desert Crate" in Beacon.
