### ISSUE TITLE
Window is stuck at top of screen and I can't move it as the title is off the screen

### ISSUE THREAD

**Issue by cyberangel67** [thommcgrath/Beacon#196]
Window is stuck at top of screen and I can't move it as the title is off the screen, I recall this was supposed to fixed, any clue how to fix this.

**Comment by thommcgrath** [comment]
Yeah, I'm looking at the code and I'm not seeing how that's possible. Sorry about the delay in my reply, I never got a notification of the new case. If you have not solved the issue yet, your best option is to reset your preferences. Go to %AppData%\The ZAZ\Beacon and delete the Preferences.json file.

**Comment by cyberangel67** [comment]
That's ok, the program told me that there was an update and the update automatically released the Window from off the top of the screen.

So for now, I was more looking for what I needed to remove to fix it, as I recall that was a solution once before. But now that the update has fixed it, I don't need to delete that information.
