### ISSUE TITLE
1.5.0a1 Bug - MOTD Adds Excessive Spaces

### ISSUE THREAD

**Issue by YarbySauce** [thommcgrath/Beacon#216]
The Message of the Day section of the Server config page adds excessive \n for each row of the message. It does this automatically.

**Comment by thommcgrath** [comment]
Can you give me an example of what you're seeing? I can't reproduce a problem. I get one newline (\n) for every line break I put in the field.

**Comment by YarbySauce** [comment]
![motd2](https://user-images.githubusercontent.com/44554851/101229700-85dc2900-366f-11eb-9b7c-0c7d80c7b9a4.PNG)
![motd1](https://user-images.githubusercontent.com/44554851/101229701-8674bf80-366f-11eb-9d80-632413b27cb6.PNG)

It also crashes if I have more than 1 server and try to switch between the 2.

**Comment by YarbySauce** [comment]
Every time I open the project, it adds more line breaks.
![motd3](https://user-images.githubusercontent.com/44554851/101229825-174b9b00-3670-11eb-8bf3-945aacfe66b6.PNG)

**Comment by YarbySauce** [comment]
To further add to this, this bug is making the Alpha release unusable to do more testing. Each & every time it refreshes it adds new \n line breaks.

**Comment by thommcgrath** [comment]
Don't worry, I'll make sure this is taken care of for alpha 2. Not much I can do about it until then.

**Comment by YarbySauce** [comment]
Thank you.

**Comment by thommcgrath** [comment]
There may be one more duplication as the data appears to be saved with \r\n on Windows, which is the cause of the issue. You'll need to manually correct the MOTD, but it shouldn't happen again.
