### ISSUE TITLE
1.5.0a1 Bug - Project Tabs "Selected" tab is not active tab

### ISSUE THREAD

**Issue by YarbySauce** [thommcgrath/Beacon#219]
There is a bug where the "selected" tab is not shown as the active "purple bar" tab.
![selectedServer](https://user-images.githubusercontent.com/44554851/101527341-ddbeac80-395b-11eb-972c-4ac8b0bf2e2a.PNG)

**Comment by YarbySauce** [comment]
I was working on Scorched, but the app had Extinction as the "selected" tab.

**Comment by YarbySauce** [comment]
Happens when you open multiple files at once & selecting different project tab cycles through the active one.

**Comment by thommcgrath** [comment]
Looks like reproduction steps have been found. I have not confirmed this myself yet though: https://discord.com/channels/323110888452390913/323110888452390913/790247222506684447
