### ISSUE TITLE
Beacon update 1.5.0.2 broke project and when deploying to Nitrado it went to official settings. 

### ISSUE THREAD

**Issue by MaltronCraft** [thommcgrath/Beacon#221]
After I recently updated to Beacon 1.5.0.2 I ran into an issue when trying to deploy my beacon project which worked perfectly fine before the update. Once I updated, the config has gotten weird when exporting. For example, I got weird ASCII characters for one setting at the end of the export while another duplicated itself multiple times and I am not sure if this happened before but the comments inside custom config are being added to the export/deployment. Once deployed to Nitrado, it got even weirder.. I will be providing a link to the .ini files that I downloaded from my Nitrado server.

INI: https://mega.nz/folder/iKRnmSZD#cWMAru2jLBIpMQuIqimtaQ

One setting being duped:

OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0
OverridePlayerLevelEngramPoints=0

Weird ASCII in export:

PlayerBaseStatMultipliers[7]=ⅱ

Nitrado view of Game.ini after deploying:

PlayerBaseStatMultipliers[7]=�
W*�
W*X�Up
W*������������(@�<Q�p
W*�
W*��N��'exӫ�U�7*0�)*��(@���H
PlayerHarvestingDamageMultiplier=50

**Comment by thommcgrath** [comment]
OverridePlayerLevelEngramPoints is normal, that comes from the unlock points list in Beacon's Engram Control editor. The way Wildcard set it up is strange, but the first row is for level 1, second for level 2, and so on.

As for the strange data in your files, I have no idea. I've never seen that before. Are you able to attach your Beacon project? Or if it's saved to the cloud, I could find it in the database if I know the name to look for. I'm hoping to release some fixes in 1.5.0.3 either today or tomorrow, so if this is something Beacon is doing wrong, I'd love to include a fix for it.

**Comment by MaltronCraft** [comment]
Yeah, I have it in the cloud https://api.usebeacon.app/v2/document/c70db5b1-b245-463c-abec-6da637643902?name=Infamous%20cluster

**Comment by MaltronCraft** [comment]
> OverridePlayerLevelEngramPoints is normal, that comes from the unlock points list in Beacon's Engram Control editor. The way Wildcard set it up is strange, but the first row is for level 1, second for level 2, and so on.

Ohh, that is quite strange.

**Comment by thommcgrath** [comment]
So the comment from custom config being included is definitely a bug. The weird characters... that's harder to explain. To computers, all numbers have a maximum value. Limits such as 255, 65535, 2147483647, and 4294967295 are depending on the type of number the program uses. Beacon stores stat limits as a double, which has a can store 15 digits accurately. You have 21 digits, so... yeah things are going wrong. Many of your stat limits are well beyond what Ark is able to handle too, as Ark has much smaller limits due to console's limited memory. If I recall correctly, the maximum number of points available to a player is 255, and the maximum value of a stat is 2,147,483,647. So with a multiplier of 100,000,000,000,000,000,000 as you've given it, you're well beyond the limit after just one point. The effect wraps back around to zero and counts up again, so since the value is so high you may not notice exactly, but I expect you're having some weird behaviors because of that.

I'll get the commenting bug fixed, but I don't think I can do anything about the numbers. Bring them down into a more sane range and I expect things will get better.

**Comment by MaltronCraft** [comment]
Alright, didn't think of the numbers causing the issue

**Comment by MaltronCraft** [comment]
Yeah, it no longer creates the ASCII after lowering the numbers. Thanks for your help! :)

**Comment by thommcgrath** [comment]
Fixed with 4e7eff5dfa475144cffd5cce1981e777876b1abc
