### ISSUE TITLE
[Request] A new column in Engram Control for the mod name.

### ISSUE THREAD

**Issue by Fing3rz** [thommcgrath/Beacon#234]
With a long modlist it becomes very difficult to navigate the engram list without knowing where each engram originates.

**Comment by Fing3rz** [comment]
Is this possible? It would improve engram editing ten fold.

**Comment by thommcgrath** [comment]
Sorry about forgetting to reply. Yes it'd be technically possible. I can't promise it'll happen, but I see no reason it couldn't happen.
