### ISSUE TITLE
ConfigAddNPCSpawnEntiresContainer malformed in ini

### ISSUE THREAD

**Issue by brown-star** [thommcgrath/Beacon#239]
The add npc is malformed and is ignored.

Example from beacon:
ConfigAddNPCSpawnEntriesContainer=(NPCSpawnEntriesContainerClassString="DinoSpawnEntriesBeach_C",NPCSpawnEntries=((AnEntryName="Beach_Add",EntryWeight=0.2,NPCsToSpawnStrings=("Moth_Character_BP_C"))))

Should read:
ConfigAddNPCSpawnEntriesContainer=(NPCSpawnEntriesContainerClassString="DinoSpawnEntriesBeach_C",NPCSpawnEntries=((AnEntryName="Beach_Moth_Add", EntryWeight=0.2, NPCsToSpawnStrings=("Moth_Character_BP_C"))),NPCSpawnLimits=((NPCClassString="Moth_Character_BP_C", MaxPercentageOfDesiredNumToAllow=0.01)))

**Comment by thommcgrath** [comment]
I'm not seeing a problem here. You get the second version from Beacon just fine if you include the limit.

**Comment by brown-star** [comment]
OMG...you are completely correct. I did not even notice the limit feature in the bottom window...thank you.
