### ISSUE TITLE
Beacon Forgets Presets

### ISSUE THREAD

**Issue by JerryYOJ** [thommcgrath/Beacon#245]
Beacon forgets the preset I used to create a custom loot drop once I've closed or reloaded the project.
I think this is a bug and should be easy fix, it's very annoying for a person who needs to alter and update presets all the time.

**Comment by thommcgrath** [comment]
Can you give me more steps to reproduce this? I haven't had any luck doing so.

**Comment by JerryYOJ** [comment]
My description of the problem is not very accurate. When you add an item set into an drop, and create a preset with it, the beacon wont set the drop to have the preset I just created. Beacause of that, I thought the beacon was forgetting which preset I used.

**Comment by JerryYOJ** [comment]
Got any plans to fix htis bug?

**Comment by thommcgrath** [comment]
Yes, it will be included in the next Beacon 1.6 prerelease, which will be either alpha 6 or beta 1.
