### ISSUE TITLE
Beacon should add more remote servers #Request

### ISSUE THREAD

**Issue by JerryYOJ** [thommcgrath/Beacon#246]
I'm currently in China and struggle to login to my beacon account. And visiting usebeacon.app without a vpn results in an connecting error.
Now, I couldnt use any omni perks and my cloud save is inaccessable.
So, if it's possible, please add some more remote servers around the world so people like me can have faster and more convenient connecting.
(Oh, and putting beacon in a global vpn doesnt seem to work, so dont suggest that anymore)

**Comment by thommcgrath** [comment]
Implemented. Beacon now uses multiple servers around the globe.
