### ISSUE TITLE
FishingLootQualityMultiplier and SupplyCrateLootQualityMultiplier values are not stored

### ISSUE THREAD

**Issue by babsgosgens** [thommcgrath/Beacon#248]
Hi,

I'm having an issue with the loot quality settings not being saved. I recorded the issue so you can see what's happening:

https://user-images.githubusercontent.com/1268142/172046247-2a7af26c-f884-4a00-adc4-113d1d374b5c.mov

Running Beacon 1.6.0.4 (The previous version had the same issue).

**Comment by thommcgrath** [comment]
I can see it happening in the video, but even with your project, I just can't reproduce it. Even trying to replicate your clicks as close as I can, I don't see it. It's definitely confusing. Try using the red X to remove the setting and see what happens. If it stays removed / not bold, try changing it to your desired value and see if that sticks.

**Comment by babsgosgens** [comment]
Removing the value by clicking x didnt work, but when I entered the value with a comma rather than a dot, it stuck. Maybe a locale issue? I'm glad it works now. A minor inconsistency I guess :) Thanks for the Sunday reply, respect 👍

**Comment by thommcgrath** [comment]
Oh, that should be up to your system settings. Beacon parses the input according to your system's locale.

**Comment by babsgosgens** [comment]
likely, yes. my decimals are comma separated. Thanks!
