### ISSUE TITLE
[BUG] Redwood spawn entry not exported [1.6.1.1]

### ISSUE THREAD

**Issue by Touhma** [thommcgrath/Beacon#258]
![image](https://user-images.githubusercontent.com/8696405/188940520-fda1f71a-efe0-4d49-a387-9b134edd8ee0.png)

**Comment by thommcgrath** [comment]
Without knowing the map I can't say for certain, but this is almost certainly the correct behavior. `Redwoods` is only used by Ragnarok, Valguero, and Fjordur. `DinoSpawnEntriesRedwoods_LostIsland_C` (which needs a human name) is used by The Island, The Center, Crystal Isles, and Lost Island.

**Comment by Touhma** [comment]
ALright my bad I mixed both spawn name then ^^
