### ISSUE TITLE
Beacon freezing when importing database updates.

### ISSUE THREAD

**Issue by AGuyOnline** [thommcgrath/Beacon#263]
Whenever I try to open beacon it tries to import database updates and freezes.

**Comment by thommcgrath** [comment]
Go to `%AppData%\The ZAZ\Beacon\Libraries` and delete any of the Ark files in the folder. Beacon will build a new database at the next launch.

In the future, use https://usebeacon.app/help/contact for support requests. GitHub issues are better for bug tracking.
