### ISSUE TITLE
MinQuality MaxQuality issues

### ISSUE THREAD

**Issue by rehv** [thommcgrath/Beacon#27]
Hi! 

I use Beacon v1.0.0b4 (Build 11), and tried to edit a few saddle overrides. In game, I've put every saddle in a 1x beacon from Primitive to Ascendant, and in 2x beacons from Ramshackle to Ascendant.

However, when exporting to text, I get some values with MinQuality = 0 and MaxQuality = 7 and some with MinQuality = 0.625 and MaxQuality = 2.80. Example:

From 1x beacon:
`("PrimalItemArmor_MantisSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=7.000000`

From 2x beacon:
`("PrimalItemArmor_MantisSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.625000,MaxQuality=2.800000`

I'm not using custom presets, I just duplicated the source from the 1x Red beacon to 2x Red beacon. The example is with saddles but happens with every kind of item, and not only between their 1x and 2x versions but also with "single" entries like in Deep Sea:
`
("PrimalItemArmor_DunkleosteusSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=1.750000`

I've "normalized" those using Regex, but wanted to know if there's a particular reason for this or if it's a known bug. Thanks in advance!

**Comment by rehv** [comment]
Ok, just for the sake of it, I tried importing the game.ini back to beacon, and found out that even though I set every single MinQuality MaxQuality to the same value, 1x, 2x and deep sea values show completely different. Does the game treat MinMax Quality values differently for each of those (and you're replicating it) or is it a Beacon bug?

**Comment by rehv** [comment]
Well, it appears to be hardcoded by WC. While I still believe the values set by the program are a bit too high, case closed :) thanks.

**Comment by thommcgrath** [comment]
See my last comment in https://github.com/thommcgrath/Beacon/issues/24 for additional details. Short answer: yes, there is some hard coding going on. Beacon has logic to help counter that though.

**Comment by rehv** [comment]
Thanks for your reply. I should have read the old issues :p

Can we have a option to adjust the scale of name <> value!? 7.0/2.8/1.75
for ascendant values give me waaaay too much of them. For example 4/1.6/1.0
already gives me a bit more ascendant drops than I'd like to.

For now, I'm using regex to adjust it so it's not really bad, but if it's
possible I think this would allow fine tuning perfectly. Thanks!

Em 15 de fev de 2017 19:21, "Thom McGrath" <notifications@github.com>
escreveu:
