### ISSUE TITLE
Cannot get Auth from Nitrado to edit server

### ISSUE THREAD

**Issue by Keens-Summit** [thommcgrath/Beacon#278]
Trying to import another server, but when I try to grant access via Nitrado, it says
"Nitrado did not authorize the request. The response was:"

But then it just has a blank text box. I want to use the same settings for two servers in my PS4 cluster.

Could not submit ticket via email, it said "Unable to upload to Zendesk"

**Comment by thommcgrath** [comment]
This was a DNS outage with Vultr. It has been resolved for a while now.
