### ISSUE TITLE
Maps Dialog Box is Too Narrow on ASA Projects

### ISSUE THREAD

**Issue by saluce65** [thommcgrath/Beacon#288]
The Maps dialog box is too narrow on Ark: Survival Ascended. It looks like the dialog is auto-fitting the body content of the dialog, which, since it only has the option for The Island, is making the OK button almost completely outside the dialog box bounds. Atached is a screenshot showing the dialog box.

<img width="75" alt="image" src="https://github.com/thommcgrath/Beacon/assets/1412484/1fababa7-f2c5-4e82-9e31-6d20c2ac23d9">

**Comment by thommcgrath** [comment]
This one was just fixed in 84ddb84d98eb4632465cf8004677ecd898c08899
