### ISSUE TITLE
Options for Photo Mode Missing

### ISSUE THREAD

**Issue by saluce65** [thommcgrath/Beacon#290]
Ark: Survival Ascended has added new options for Photo Mode:

`bDisablePhotoMode`, a boolean that defaults to `False`
`PhotoModeRangeLimit`, an integer number that defaults to `3000` and defines how far away from the character you are allowed to go when using Photo Mode.

**Comment by thommcgrath** [comment]
Photo mode settings have been added as of the `October 30th, 2023 at 4:52 PM UTC` data update.
