### ISSUE TITLE
No servers found Nitrado

### ISSUE THREAD

**Issue by rbthibod** [thommcgrath/Beacon#299]
I just bought a nitrado server this morning for asa, i cannot get or find any server even after giving permission. it just says no ark servers found for pc xbox or ps.

**Comment by thommcgrath** [comment]
For future reference, GitHub Issues is better for bug reports. For help tickets, create the ticket from Beacon's help menu or https://usebeacon.app/help.

The stable version of Beacon doesn't yet support ASA. Download 2.0 Beta 3 from https://usebeacon.app/download to use Beacon with ASA.
