### ISSUE TITLE
error while starting editor

### ISSUE THREAD

**Issue by v4mpir3lord** [thommcgrath/Beacon#30]
Hi, 
I installed your programm to use it for my ark server but when i want to launch it i get following error:

an exception of class xojo.IO.IOException was not handled.

Any ideas how i can fix it?

Thanks for your help!

**Comment by thommcgrath** [comment]
Unfortunately I need more details. What were you doing? It sounds like you simply tried to launch the program. An I/O exception means it cannot write to disk for some reason, are you on a write-protected or full volume?

**Comment by v4mpir3lord** [comment]
Thanks for your fast answer! :)
Yeah, i just wanted to simply launch the program. I am on a normal HDD, not write-protected or full. Every other program i am installing is launching without any error... I really don´t have an idea what could be the problem here. When i try to launch an window is opening with the error and after i click it away the program is starting but instantly closing again(in less than a second).

**Comment by thommcgrath** [comment]
Hmmmm. I'm stumped. Does the dialog give you a location? Usually it will say something like "Unhandled x in y" that will at least give me a clue.

If I had to guess, it is something to do with how Beacon sets up its local user files. But I don't really have any idea how that could be going wrong.

Check for %AppData%\The ZAZ\Beacon\Events.log and post it here, if it exists. Unhandled exceptions will get logged there. Do not post other files from that folder, just the log file.

**Comment by v4mpir3lord** [comment]
Thanks again for your help!

the Events.log says this:

2017-02-25 16:06:45.1920000000 Europe/Berlin	Beacon finished gracefully
2017-02-26 02:27:57.3760000000 Europe/Berlin	Beacon 12 for Windows.
2017-02-26 02:27:57.3930000000 Europe/Berlin	Checking for engram updates from https://thezaz.com/beacon/classes.php?version=12&changes_since=2017-02-23%2017%3A20%3A03
2017-02-26 02:27:57.7660000000 Europe/Berlin	Creating new identity
2017-02-26 02:27:58.0250000000 Europe/Berlin	Unhandled xojo.IO.IOException in : This file could not be opened
2017-02-26 02:27:58.0760000000 Europe/Berlin	Engram check error: Im Support des sicheren Channels ist ein Fehler aufgetreten

There is an Error in the support of a safe channel...

**Comment by thommcgrath** [comment]
In the folder there is a Default.beaconidentity file. Or at least there should be. The error log is created, so write permission is possible, so I have no idea why Beacon wouldn't be able to write to it.

The logs say it tries to create that file, then the error happens. Do NOT post that file here. If it exists, delete it. If it does not exist, delete the entire folder. Beacon will create it again.

That final error also concerns me, but we'll work on one issue at a time.

Which version of Windows are you using?

**Comment by v4mpir3lord** [comment]
Okay thank you! I use Windows 7 with an Alienware Brand....maybe thats the problem

**Comment by thommcgrath** [comment]
Ok. Win7 may be to blame for the engram check error, but I wouldn't expect for anything else. Alienware shouldn't matter at all.

Try creating an empty Default.beaconidentity file. It won't solve your problem, but hopefully Windows will give you a similar error that may have more details.

I have to admit, something feels wrong with your drive. Maybe formatted differently or something. Why one file can write and another cannot in the same folder is completely bizarre. We'll figure it out though.

**Comment by v4mpir3lord** [comment]
Hmm. I did so but there is still the same Error as always. 

I also tried to install your program on my other SSD where my windows is but same error....

**Comment by thommcgrath** [comment]
No, changing the install path of Beacon won't change where it stores user files. But you were able to create the identity file ok?

Can you post the full path to that Beacon folder in %AppData%? I've got a long shot of an idea.

**Comment by v4mpir3lord** [comment]
yeah, i hope i did it right but i did.

C:\Users\MyName\AppData\Roaming\The ZAZ\Beacon is the full path.

**Comment by thommcgrath** [comment]
Heh. The "myname" part is what I'm most interested in actually. I suspect, given your nationality, there a possibility of an encoding issue.

**Comment by v4mpir3lord** [comment]
Oh, it might be my username....i have an é in my name...
Now i remember FIFA15 or so had a problem with that too..i needed to make a new user on my computer to start the game without error.

**Comment by thommcgrath** [comment]
Great! I bet I can fix the bug on my end.

**Comment by v4mpir3lord** [comment]
After some time of understanding everything is working...running the server now in expert modus. Used your program to create the code for beacons and uploaded the game.ini file with the other settings to my server and its running now! 

Thanks a lot for your help! You are a cool developer! Go on with your good work man!

Greetz from germany! :)
