### ISSUE TITLE
Ark Asa Breeding Multipler times different

### ISSUE THREAD

**Issue by MoldyTaint** [thommcgrath/Beacon#304]
Beacon is pulling via SFTP from my server, I can assure that the files do not get overwritten when the server restarts as they're the same after it starts too.

I tested mating two Pteranodon which should have a baby incubation time of 3m 20s at 40x. In game this is around 20s instead.

**Comment by thommcgrath** [comment]
You have single player mode turned on. You can either turn it off, or use the "Rates" button at the top of the Breeding Multipliers editor to view the results table using single player rates.

**Comment by MoldyTaint** [comment]
> You have single player mode turned on. You can either turn it off, or use the "Rates" button at the top of the Breeding Multipliers editor to view the results table using single player rates.

Well hold me silly and tickle me pink, you're a life saver!
