### ISSUE TITLE
Change Cryofridge and Cryopod Default Engram Unlocks for ASA

### ISSUE THREAD

**Issue by saluce65** [thommcgrath/Beacon#307]
Default unlocks for engrams for cryopods and cryofridge are incorrect. Currently, creating a new project lists the cryofridge unlocking at level 88 for 60 points and cryopods unlocking at 51 for 20 points. However, ASA, they are both unlocked at level 50, with the cryopod being 12 points and the cryofridge being 20 points.

<img width="458" alt="image" src="https://github.com/thommcgrath/Beacon/assets/1412484/8c71bdf8-dd32-4260-89c7-47a46a1d6d56">

**Comment by thommcgrath** [comment]
Ok, these have been updated.
