### ISSUE TITLE
Can't import huge config

### ISSUE THREAD

**Issue by astappev** [thommcgrath/Beacon#31]
I tried to import [this](https://gist.github.com/astappev/3791738daf1d787b7b5f005369ce5090) config file and it loaded only one record. Then I tried to import only first line from the file and nothing was loaded.

Can you check what is wrong?

Thank you

**Comment by thommcgrath** [comment]
Perfect. I'll check it out as soon as I have time.

**Comment by astappev** [comment]
I tried to investigate into the issue and found something

So, it happens because my config contains space characters between keys and when Beacon trying to read the config, it also read this spaces and therefore has wrong keys.

As a solution I propose to add something like trim() for each key in Import function.
As temporary solution I removed all spaces from my config.

This screenshots can help you to understand what I mean
![2017-02-27_113732](https://cloud.githubusercontent.com/assets/4512729/23358396/119328f2-fce2-11e6-858a-a18efdee7b39.png)
![2017-02-27_113642](https://cloud.githubusercontent.com/assets/4512729/23358556/ca303440-fce2-11e6-8d61-ebeb7413cf89.png)

**Comment by astappev** [comment]
Unfortunately, it is first time when I meet Xojo and I don't have enough knowledge to create pull request.

**Comment by thommcgrath** [comment]
Very cool. Thanks for the help.

Also, I noticed when importing your config that you have a typo. It should be PrimalItemConsumable_Soup_FocalChili_C - you have an extra L in Chili.

**Comment by astappev** [comment]
I know, the config include too much mistakes, I took it from this [topic](https://www.reddit.com/r/playark/comments/54045n/augmented_supply_drop_code_v4/).
