### ISSUE TITLE
Mod data has disappeared

### ISSUE THREAD

**Issue by cyberangel67** [thommcgrath/Beacon#312]
Ok so I had added my mod to beacon and spent a few days adding all the information, someone pointed out to me that the info for the engram was incorrect and I had just gone through adding all this information correctly.

Took me about 2 hours.

When I finished it would not publish, when I tried to save it, it would not save.

And then I had about 100 save boxes when I tried to close it.

Now, when I try to import the old save, it not only will not import it, but I can not even see my mod to readd anything manually.

**Comment by thommcgrath** [comment]
Do you happen to know the error message you received when trying to publish?

In the future, the best option is to use the Export button so you can at least save the work to the computer. It can be imported back into the mod later, as well as help with debugging.

**Comment by thommcgrath** [comment]
Unfortunately there is not a lot I can say or do at this point. I'm going to have to close the issue.
