### ISSUE TITLE
Adding mod items

### ISSUE THREAD

**Issue by Daulken** [thommcgrath/Beacon#33]
Hey there, I've been trying to add items from a mod we use to the beacons, and I'm finding it a little unclear on exactly how to do that.

First, while I did figure it out, typing the entire class string in the filter and then clicking the checkbox works fine, but that's a pretty non-standard UI and might be worth mentioning in your Getting Started guide.

Then, I'm not entirely sure what to put, although it does seem like it should only be the final part of the string, take for instance one of the very popular mods out there.  To spawn in the item, we need this full string:

"Blueprint'/Game/Mods/StructuresPlusMod/Structures/Walls/Thatch/PrimalItemStructure_Wall_Thatch.PrimalItemStructure_Wall_Thatch'"

I've been trying various combinations of the above, from what I think is most likely to least likely, but I'm not entirely sure what I should be putting, and the cycle for trying something and testing it on a remote server is long.

Any help on exactly what I should be putting, or quicker cycles to test?

Thanks!

**Comment by thommcgrath** [comment]
PrimalItemStructure_Wall_Thatch_C would be the correct string. At least for the built-in items, the class strings always end in _C for some reason.
