### ISSUE TITLE
some drops don't work

### ISSUE THREAD

**Issue by arkfrance** [thommcgrath/Beacon#34]
Hi, 

i've tried your soft and really like it ! Thanks for that !

i've some problem to make it works, i've made this : 

ConfigOverrideSupplyCrateItems=(SupplyCrateClassString="SupplyCrate_Level35_C",MinItemSets=1,MaxItemSets=3,NumItemSetsPower=1.000000,bSetsRandomWithoutReplacement=true,ItemSets=((MinNumItems=1,MaxNumItems=5,NumItemsPower=1.000000,SetWeight=0.500000,bItemsRandomWithoutReplacement=true,ItemEntries=((EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_FurPants_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_FurPants_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_FurShirt_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_FurShirt_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_FurHelmet_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_FurHelmet_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_FurBoots_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_FurBoots_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_FurGloves_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_FurGloves_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0))),(MinNumItems=1,MaxNumItems=2,NumItemsPower=1.000000,SetWeight=0.500000,bItemsRandomWithoutReplacement=true,ItemEntries=((EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_DoedSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_DoedSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_CarnoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_CarnoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_Gallimimus_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_Gallimimus_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_AnkyloSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_AnkyloSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_ArgentavisSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_ArgentavisSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_TapejaraSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_TapejaraSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_TrikeSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_TrikeSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_MammothSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_MammothSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_RhinoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_RhinoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_SarcoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_SarcoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_StegoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_StegoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_ParaSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_ParaSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_DireBearSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_DireBearSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_TurtleSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_TurtleSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_MegalodonSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_MegalodonSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_PelaSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_PelaSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_KaprosuchusSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_KaprosuchusSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_ChalicoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_ChalicoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_MegalosaurusSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_MegalosaurusSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_PachyrhinoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_PachyrhinoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_TherizinosaurusSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_TherizinosaurusSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_BaryonyxSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_BaryonyxSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.900000,ItemClassStrings=("PrimalItemArmor_ThylacoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.100000,ItemClassStrings=("PrimalItemArmor_ThylacoSaddle_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0)))))

When i spawn it, it auto dissapear, is there a problem with the synthax ?

Thanks

**Comment by thommcgrath** [comment]
Syntax looks fine to me. I don't know what the issue could be.

**Comment by arkfrance** [comment]
if you add the thatch housing in a loot, it doesn't work for me in any beacons, auto dissapears

**Comment by arkfrance** [comment]
for this drop, why there are duplicated saddle ? this comes from the Medium Saddles

**Comment by arkfrance** [comment]
Any clue?

**Comment by thommcgrath** [comment]
I know the duplicated entries are due to how I've handled the blueprint chance. Ark is weird, what Beacon produces is most similar to what is expected. As for the actual problem you're having, I just don't know. Can you share your Beacon file itself, rather than the ini syntax? It should be easier for me to understand your intentions.

**Comment by arkfrance** [comment]
i've found the problem, it came from the map or a mod itself

**Comment by thommcgrath** [comment]
Ok, good to know. Sorry I wasn't able to be of more help.
