### ISSUE TITLE
Window frozen bug

### ISSUE THREAD

**Issue by Darkblood18** [thommcgrath/Beacon#35]
Hey! Let me start by congratulating you on this amazing piece of work, I love it.

In one of my computers I'm having a issue with the preset library. It is 100% reproducible:

1) open beacon
2) open preset library
3) New 
4) On the "Create Preset" Window click on "Add"

The "Set Entry" window opens up but nothing on it is clickable (when you try to click on any field you get the Windows 7 "Default Beep" sound, like when you are supposed to be clicking on another window). Buttons are frozen too, so you cannot cancel nor continue. The "Create Preset" and "Preset Library" are also frozen in the same way (although I guess they are supposed to while "Set Entry" is open). The only way out of this is by using Task Manager to kill Beacon.

There are no visual glitches or other signs of crashing, it is really like there is some additional dialog which is not showing and Beacon is waiting for it.

This is on Windows 7 SP1, let me know if you need extra info on my system.

**Comment by Darkblood18** [comment]
Forget it, solved in Beta 7 (I had Beta 6 installed)

**Comment by thommcgrath** [comment]
Yeah, this bug is pretty much the only reason B7 exists.
