### ISSUE TITLE
Rendering problems on win 7 sp1

### ISSUE THREAD

**Issue by Darkblood18** [thommcgrath/Beacon#38]
I'm getting a graphical but on both my Win 7 machines (SP1) looks like this:

![image](https://cloud.githubusercontent.com/assets/25591231/25104759/f79e37e8-2397-11e7-8f5c-558d66e15203.png)

(note the missing checkboxes by each entry in the content list)

This happens with all presets 100% of the time. The checkboxes are still "clickable" but it takes some guessing to know if they are checked or not. My Win8 box shows everything just fine.

Let me know if you need extra info on my system.

**Comment by thommcgrath** [comment]
Hey sorry about such as massive delay, but I just stumbled upon the solution to this issue. It seems like Windows needs the [KB2670838](url
https://support.microsoft.com/en-us/help/2670838/platform-update-for-windows-7-sp1-and-windows-server-2008-r2-sp1) update installed.
