### ISSUE TITLE
Custom Items

### ISSUE THREAD

**Issue by steve66** [thommcgrath/Beacon#48]
I know in the description it says it can support custom items by putting in the class string.. but for the life of my I can't figure out how?  Where would I do that?

I want to add in all S+ items instead of the normal structure items.

**Comment by thommcgrath** [comment]
When adding an item to a set, enter the complete class string into the filter field. An item with exactly what you entered will always be shown at the bottom of the list. Check it off, and continue adding the item like any of the built-in ones.

**Comment by steve66** [comment]
oh interesting, thx.

**Comment by steve66** [comment]
I have been trying to get s+ items to spawn in drops and so far none of that color are even coming down, my guess is bad data within then.

For the class string, is this it, with the " at start and end?
"Blueprint'/Game/Mods/StructuresPlusMod/Crafting/Station/PrimalItemStructure_SPlusCraftingStation.PrimalItemStructure_SPlusCraftingStation'"

**Comment by thommcgrath** [comment]
I'll make sure this is more clear in the future somehow.

The class string for that item is PrimalItemStructure_SPlusCraftingStation_C - it's the last part after the "." plus _C at the end. Ark is weird. But I'll find a way to make this better.

**Comment by steve66** [comment]
Also it seems I am having trouble editing my custom option too.  Its not appearing at the bottom to rename it.  My last entry in the Set Entry window is Yutyrannus Saddle when I edit it from the Preset.

**Comment by thommcgrath** [comment]
Oh boy, that's not good. This definitely needs some work. The only way I was able to get it to appear was to enter the exact wrong string first, uncheck that, then enter the exact correct string and check the new result.

**Comment by thommcgrath** [comment]
Custom item management has been greatly improved in checkin https://github.com/thommcgrath/Beacon/commit/9819842b166722c76850862be8c181cea6ee8025
