### ISSUE TITLE
Missing item - Kibble (Pegomastax Egg)

### ISSUE THREAD

**Issue by Windsinger1985** [thommcgrath/Beacon#50]
Hi, 

I cannot add the Kibble (Pegomastax Egg) to my presets, 

Item : PrimalItemConsumable_Kibble_PegomastaxEgg_C
It's listed in the http://ark.gamepedia.com/Item_IDs/Consumables list.

Ps, keep up the great work <3

Regards,
Windsinger

**Comment by thommcgrath** [comment]
Good catch. All set now.
