### ISSUE TITLE
Getting higher quality than intended

### ISSUE THREAD

**Issue by NuggetMonster** [thommcgrath/Beacon#51]
Love your app, great work :)

Ive been using a custom loot table for 2 months or so, created with Beacon. On at least 2 occasions I have received items of higher quality than they are set to spawn in as. Im hesitant to give a ball park on how many beacons/crates Ive looted in that time, it would be in the low 3 figures, ie this is a very rare occurrence. Not the end of the world by any means!

This just happened again now, so I figured I would go out and look at the code responsible. I looted Ascendant quality Ghillie boots. According to Beacon, the max quality should be Journeyman. The code is as follows

(EntryWeight=0.200000,ItemClassStrings=("PrimalItemArmor_GhillieBoots_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=1.363636,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0)

Ive gone and confused myself further... The line above is from an X2 beacon (if that matters), for my own curiosity really I went to look at the code for the regular version of this drop, which I have set to cap at Apprentice quality. The full set for this looks as follows

(MinNumItems=2,MaxNumItems=6,NumItemsPower=1.000000,SetWeight=0.490000,bItemsRandomWithoutReplacement=true,ItemEntries=((EntryWeight=0.225000,ItemClassStrings=("PrimalItemArmor_GhilliePants_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.025000,ItemClassStrings=("PrimalItemArmor_GhilliePants_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.225000,ItemClassStrings=("PrimalItemArmor_GhillieShirt_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.025000,ItemClassStrings=("PrimalItemArmor_GhillieShirt_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.225000,ItemClassStrings=("PrimalItemArmor_GhillieBoots_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.025000,ItemClassStrings=("PrimalItemArmor_GhillieBoots_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.225000,ItemClassStrings=("PrimalItemArmor_GhillieGloves_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.025000,ItemClassStrings=("PrimalItemArmor_GhillieGloves_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=0.225000,ItemClassStrings=("PrimalItemArmor_GhillieHelmet_MyMod_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0),(EntryWeight=0.025000,ItemClassStrings=("PrimalItemArmor_GhillieHelmet_MyMod_C"),ItemsWeights=(1.000000),MinQuantity=1,MaxQuantity=1,MinQuality=0.000000,MaxQuality=2.000000,bForceBlueprint=true,ChanceToBeBlueprintOverride=1.0),(EntryWeight=1.000000,ItemClassStrings=("ToolRepairKit_C"),ItemsWeights=(1.000000),MinQuantity=2,MaxQuantity=4,MinQuality=0.000000,MaxQuality=0.000000,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0)))

The reason I am including this is because I know I have looted this particular drop (and set) 15 times or more and have never received higher than Apprentice quality. The reason I am confused is because I see the max quality is "2.0", but on the X2 table which is set to cap at Journeyman, the max quality is "1.363636". Im sure there is logic in there somewhere, but its lost on me!

...And I should stop looking at this code! Sorry, this is spilling out into another maybe-issue, or *more* likely I just dont understand what Im reading ><! All of the armor items quoted should have a chance to be a blueprint, with the same % on each. So why do some have the bForceBlueprint=true, and some "false" :s Some have ChanceToBeBlueprintOverride=0.0, and some "1.0". They were all grouped and given a value, shouldnt they all have the same values in those fields? o.0;

**Comment by thommcgrath** [comment]
I believe this will answer all (or most) of your questions. https://thezaz.com/beacon/why.php

Read it over and feel free to follow up with additional questions if you need.

**Comment by NuggetMonster** [comment]
Yes, thank you, that was helpful! Summarized nicely in this sentence "This is because Ark is weird."

I had read some random threads before setting out to create a custom loot table and vaguely recall some references to the quirks in Ark. I guess I just got a glimpse of this in action!
