### ISSUE TITLE
Ragnarok Need the scorched earth Crates Too

### ISSUE THREAD

**Issue by Slater022** [thommcgrath/Beacon#52]
Ragnarok use a custom version of all beacons ( the Islands + Scorched, same thing for cave loots etc ..:/ ) you update just fucked up my config because of that ^^"

**Comment by thommcgrath** [comment]
Can you give me some sort of documentation? I've seen no evidence that Ragnarok uses SE crates, and I play on Ragnarok daily.

**Comment by Slater022** [comment]
Huuuum I don't really have documentation except a reddit discusion where some guy's said me taht all crates are on this map 
And With my experience today with the file generated with only ragnarok loot source from your software 
Result : Can found in some beacon SE loots table

**Comment by thommcgrath** [comment]
Link me the discussion. Anecdotally, I've only defined the island and treasure chest on my sever, and every drop we've looted has been as expected.

**Comment by Slater022** [comment]
http://ragnarokmap.wikia.com/wiki/Lootdrop_Override <- there is an example file.
https://www.reddit.com/r/playark/comments/6idc68/how_are_organized_the_loots_crates_on_ragnarok/ <- the reddit question I asked

**Comment by Slater022** [comment]
On my server i had in blue cave loot the SE version. And found in some double yellow crate / blue crate some epic version of loot from SE ( Oil Rigs etc ... )

**Comment by Slater022** [comment]
![image](https://user-images.githubusercontent.com/3940371/27757736-d754678e-5e05-11e7-92fe-b36cda5e67fa.png)

Discution on discord that confim my point ^^ ( it's a modo from the official discord )

**Comment by thommcgrath** [comment]
Ok. That's good enough for me. I cannot update the database until I'm back on Sunday though.

**Comment by Slater022** [comment]
okey :) Keep me up man. :) Your software is freaking cool :)

**Comment by Slater022** [comment]
Do you know if there is a way to customize beaver dams loots ?

**Comment by thommcgrath** [comment]
Ok, I have updated the loot sources available to Ragnarok to match those in the thread you linked.

To answer your other question, no there is not currently a way to update the beaver dams. It is something I'm interested in though.

**Comment by Slater022** [comment]
Something missing again : Desert Crates from scorched ;)

**Comment by thommcgrath** [comment]
I put in everything from that list posted last time. Do you have a means for me to contact the map developer? This still feels very weird to me.

**Comment by Slater022** [comment]
The discord :)
https://discord.gg/Mg98Zr2
they are streaming a lot while the week

**Comment by thommcgrath** [comment]
So for the record, the only crates Ragnarok uses, according to their dev kit are:

SupplyCrate_Level03_C
SupplyCrate_Level03_Double_C
SupplyCrate_Level15_C
SupplyCrate_Level15_Double_C
SupplyCrate_Level25_C
SupplyCrate_Level25_Double_C
SupplyCrate_Level35_C
SupplyCrate_Level35_Double_C
SupplyCrate_Level45_C
SupplyCrate_Level45_Double_C
SupplyCrate_Level45_Double_ScorchedEarth_C
SupplyCrate_Level60_C
SupplyCrate_Level60_Double_C
SupplyCrate_Level70_Double_ScorchedEarth_C
SupplyCrate_Level70_ScorchedEarth_C
SupplyCrate_OceanInstant_C

So that's what I'm going to set Beacon to.

**Comment by thommcgrath** [comment]
Well... and the artifact crates too.
