### ISSUE TITLE
Crashed trying to save my beacon presets

### ISSUE THREAD

**Issue by jkdoug** [thommcgrath/Beacon#56]
I did a lot of editing, but when I tried to save my changes, I encountered an unhandled NilObjectException and lost my work.

I'm modifying a file from a slightly older version of Beacon, and it also contains many items from mods, such as Structures Plus. Not sure if either of these details matters, though I suspect so.

**Comment by thommcgrath** [comment]
Sorry about that. The error comes from not having set the map (as the giant dialog suggested) before saving. Next build of Beacon will just save the file with the map missing, so you can select later.
