### ISSUE TITLE
Are import times supposed to take this long?

### ISSUE THREAD

**Issue by Rhah-** [thommcgrath/Beacon#57]
I'm experiencing incredibly long import times for an existing .ini file. I'm talking, like, 45+ minutes at the minimum to complete an import. I'm not sure what's going on behind the scenes exactly but it seems to me that parsing text shouldn't take quite _this_ long. Apart for this, the application works like it should (to the best of my knowledge, anyways).

Is this happening to everyone or am I just an isolated instance? Can anyone shed some light on this for me?

**Comment by thommcgrath** [comment]
Sounds isolated to me, but I'd like to know more. Create a new document, open your ini, copy each line, and paste them into Beacon one-by-one. This should help narrow down which line is the problem, and then we can work on it from there.

**Comment by Rhah-** [comment]
Well, the more I delve into the ini file, the more likely it seems that it works as it should. I have 54 lines of supply drop overrides and importing them one by one takes some time too. Granted it's not as long as trying to import all 54 lines at once, obviously. 54 lines at about 40,000 characters long, give or take.
 The previous server owner must had made major alterations prior to my adoption of the server. Probably should have mentioned that earlier! Sorry!

Out of curiosity, I saved the import as a new .beacon file, then exported it as a new ini, exited and restarted, and then imported the new ini and things still take just as long. So I'm chalking it up to just the sheer number of beacon edits causing the long import times. Unless you can think of something else that would cause it I think we can mark the 'issue' as a non-issue. lol.

**Comment by thommcgrath** [comment]
Ok. There may be optimizations I can make, but if it isn't actually wrong (just slow) then yes, I'll close it.
