### ISSUE TITLE
[Feature] Export to CSV

### ISSUE THREAD

**Issue by KillerInstinct** [thommcgrath/Beacon#58]
Firstly, thanks for the tool it's been super easy to learn and use!

I wanted to ask how hard it would be to export to CSV the "nice names" instead of the internal ARK BP names. Basically I want an easy way to export these 'nice names' into an excel doc, and CSV would be pretty trivial I suspect.

I tried to work with the json format, but it's a pain to find/replace all the BP names with their nice names. Thus I was wondering if this could be added.

**Comment by thommcgrath** [comment]
What is this for? It sounds outside the scope of what Beacon is used for. There are other ways to get to the data you're after though, such as the local engrams database or the Beacon API. But without knowing your actual goal, I'm not sure how best to direct you.

**Comment by KillerInstinct** [comment]
Literally just want to export the actual names to an excel doc / google sheet. Not the DinoName_C format.

**Comment by thommcgrath** [comment]
If you get an editor for SQLite, you can open %AppData%\The ZAZ\Beacon\Library.sqlite and execute `SELECT label FROM engrams` to get the list at any time. That's probably the fastest way to get to that info. SQLiteManager is a nice one, but it's not free. The sqlite3 command line app is free, available for Windows, and will even output to csv, but requires using the command line. There are lots of tools available that will let you peak inside Beacon's data.
