### ISSUE TITLE
Way to open original ARK beacon data?

### ISSUE THREAD

**Issue by Ihmislehma** [thommcgrath/Beacon#61]
Is there a way to open the original data of ARK beacons? I'm looking to modify my SE beacons, but don't want to do everything from absolute scratch. It would be helpful if these were available as a starting point option.

**Comment by thommcgrath** [comment]
They need to be copied from the dev kit one-by-one. This takes time that nobody has put in yet, mostly because the loot tables change from time-to-time.

**Comment by Ihmislehma** [comment]
That was fast! And thanks, I suppose it'd be too much work, true. 
At one page it says you can use Devkit as a source. How is this done?

**Comment by thommcgrath** [comment]
It's complicated. With the dev kit open, search for a loot source id. Inside that is a reference to a lootsource class. When you find that, you can copy that object and paste it into Beacon. Beacon knows how to parse it.

**Comment by Ihmislehma** [comment]
Okay, thanks!

**Comment by piotrch** [comment]
Hi,
I've tried copying item set from dev kit but min/max quality values are set to primitive, even in lev 60 red beacons. The same issue is with extracted values posted on your site. Is there possibly some bug in parsing data copied from dev kit?

**Comment by thommcgrath** [comment]
No, those values are correct. Each loot source has its own quality multiplier which affects the contents.
