### ISSUE TITLE
crash on offline / limited connectivity

### ISSUE THREAD

**Issue by Tlazolteotl** [thommcgrath/Beacon#63]
My company is using deep package inspection and so it is disturbing the https traffic to your site. if your app try to connect any online ressource, it will crash. So i cant Import presets on our Network. it would be nice, if you can add an offline mode.

sry for my bad language.

**Comment by thommcgrath** [comment]
First, see "Engrams are not updating" in https://beaconapp.cc/help/ for a possible solution.

If that doesn't work, please send me the Events.log file in %AppData%\The ZAZ\Beacon so I can get more details about what exactly is going wrong.

**Comment by thommcgrath** [comment]
Well I checked in a fix for a related issue earlier this morning ( https://github.com/thommcgrath/Beacon/commit/525d9a4f03298a3689072e02362be66984b7416c ) but I'm not certain it would fix your issue, because the exception type is different in your case than what I was able to reproduce.

Can you try other online functions, like the "Check for Updates" for me? It should give you an error without internet, but not an exception that would cause Beacon to die.

**Comment by Tlazolteotl** [comment]
you are right. i got the hard exeption only on the library. On update, i got an normal errormessage from your app and it wont crash. 

![update](https://user-images.githubusercontent.com/31697662/30123873-a8cb23a4-9333-11e7-98e3-45ee32426c8c.JPG)

i got an error on the second try. maybe because my Focus was on the main window by switching between app and snipping tool.

![update2](https://user-images.githubusercontent.com/31697662/30123872-a8c76ff2-9333-11e7-8da5-f88375b2c33a.JPG)

As i already written, the following exeption occurs only on the lib. I got this error also, if i try to Import some presents, because lib. is opend i think...

![library](https://user-images.githubusercontent.com/31697662/30123874-a8cc736c-9333-11e7-8325-480f14b26fba.JPG)

**Comment by thommcgrath** [comment]
Ok, so the good news is the "TypeMismatchException" has been fixed for the next build. That's what I did this morning while trying to reproduce your issue.

The bad news is the "Beacon has stopped working" is pretty much a mystery to me. I don't really have any way to track that down.

**Comment by thommcgrath** [comment]
The TypeMismatchException is fixed in the now-available beta 16: https://github.com/thommcgrath/Beacon/releases/tag/1.0.0b16

**Comment by Tlazolteotl** [comment]
Its working now. Thanks! :)
