### ISSUE TITLE
Unable to delete presets in Library

### ISSUE THREAD

**Issue by Tlazolteotl** [thommcgrath/Beacon#64]
If i try to delete a custom preset, the last built-in line was selected, but my object wont be deleted. Item can be opend after it, so it isnt only a display error. Item remains after restart also. 

![2017-09-07 11_05_08-clipboard](https://user-images.githubusercontent.com/31697662/30155482-3c9ba8a4-93bd-11e7-92e3-ba937b761aff.jpg)
![2017-09-07 11_06_28-library](https://user-images.githubusercontent.com/31697662/30155483-3c9d267a-93bd-11e7-889d-4b81779501dd.jpg)

T2 is a copy of T1... maybe this information might be useful.

**Comment by thommcgrath** [comment]
This will be fixed in beta 17
