### ISSUE TITLE
OutofBoundsException

### ISSUE THREAD

**Issue by FajitaLondon** [thommcgrath/Beacon#66]
Hello,

I am currently having an issue with the Beacons program.  Whenever I try to create a custom preset I get a popup stating "An Exception of class OutOfBoundsException was not handled.  The application must shut down."

Full Story:  I had used the software before to create custom presets and loot for vanilla ark and it worked just fine.  This issue began when I attempted to import S+ from the URL "http://pasted.co/8a4f4426".  The program stated that only 1 Engram was imported but it seemed like a garbled mess.  I wasn't sure if it was right or not so I attempted to make a new preset, that is when it first occurred.

Troubleshooting:  I uninstalled and reinstalled several times but the issue keeps occurring.  I've deleted all of the files and folders associated with this program that I can find and downloaded a new install file, but nothing has helped so far.  I have also restarted my computer between uninstall/install, to see if for some reason that would help.  

I am at my limit as far as technical knowledge and appreciate any advise I can receive.

**Comment by FajitaLondon** [comment]
Okay I managed to fix the issue on my own.

I uninstalled the program, cleared all left over beacon information from my Appdata folder and the deleted the registry keys.  Hopefully this issue doesn't bite me again when I am in the middle of something.  Anyways, I hope this helps anyone who hits the same issue.

**Comment by thommcgrath** [comment]
Sorry I hadn’t responded in time and glad you got it working. If the problem comes back, please attach your Library.sqlite file here so I can potentially reproduce the problem and find the cause.
