### ISSUE TITLE
comma separated items

### ISSUE THREAD

**Issue by JamieKG** [thommcgrath/Beacon#7]
Hi I was look on the web for the default ark beacons and I think I found them here 
https://gist.github.com/Qowyn/1ba97eaa658b3d6b27394a155ab69777
https://gist.github.com/Qowyn/a8181e73d2fc1d972e26cdfda70a423b

when importing them to Beacon I found they have comma separated items in some of the item fields that i cant edit
http://i.imgur.com/35qZHuC.png
Is this some thing that wont possible in Beacon ?

**Comment by thommcgrath** [comment]
What happens when you try to edit?

Ark supports multiple items in each set entry, each with a given weight. This allows you to create an entry with both a Quetzal Saddle and Quetzal Platform Saddle, so that a loot source will only contain one of the two. For example.

Being a somewhat niche feature which adds a significant amount of complexity, I opted not to support it. That could change I suppose, but my head spins just thinking about what the edit dialog would look like if editing multiple multi-item entries at the same time.

**Comment by thommcgrath** [comment]
Oh and by the way. Beacon will remember those items correctly. The UI may not support their creation, but they can be imported, exported, and the Beacon document format even supports them. So if you wanted to leave those in your file, it is supposed to be perfectly safe to do so. Their lack of support is only at the user interface level.

**Comment by JamieKG** [comment]
"What happens when you try to edit?"
http://i.imgur.com/udppzEy.png


Ok cool I understand the complexity and as you say I could add them and beacon will not touch them on export so its still possible for me to do if i chose to do so

**Comment by JamieKG** [comment]
So ive been thinking about this a bit im not a developer of any sort but I think this would be good
when you add new Item

![Image](http://i.imgur.com/4UExvtI.png)

then next

![Image](http://i.imgur.com/iYFZwxO.png)

if you wanted to edit the items you would press the edit icon next to classes

![Image](http://i.imgur.com/wfp6ndp.png)

then get this dialog again ?

![Image](http://i.imgur.com/4UExvtI.png)

Sorry for the bad paint skills

**Comment by thommcgrath** [comment]
That's not bad. I like the "as one entry" idea, but you wouldn't have the ability to set per item weights. I've been thinking about this feature though, and I've decided I do want to support it. I just haven't decided how yet.

**Comment by thommcgrath** [comment]
Implemented with https://github.com/thommcgrath/Beacon/commit/81041b1a5472e61b6aecad29d8546992035230ac

Setting per-engram weights has been skipped. I think this is a fair compromise. At least for now.
