### ISSUE TITLE
New skins

### ISSUE THREAD

**Issue by normanbatez** [thommcgrath/Beacon#71]
Bulbdog Mask "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_PugMask.PrimalItemSkin_PugMask'"
Reaper Helmet "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ReaperHelmet.PrimalItemSkin_ReaperHelmet'"

**Comment by thommcgrath** [comment]
Can't believe I forgot about this for so long...
