### ISSUE TITLE
[Suggestion] Simulation available at multiple levels

### ISSUE THREAD

**Issue by Tahvohck** [thommcgrath/Beacon#74]
I'd like to be able to simulate the entire contents of an inventory, or the entire contents of an item set, in order to confirm things are working as expected at higher positions in the hierarchy. Could this be broken out into its own pane at some point?

**Comment by thommcgrath** [comment]
That's the plan.

**Comment by thommcgrath** [comment]
This is implemented in the new UI.

<img width="261" alt="screen shot 2018-06-19 at 5 37 26 pm" src="https://user-images.githubusercontent.com/12851521/41625644-7a7fea62-73e7-11e8-9cd8-996861ebb69d.png">
