### ISSUE TITLE
Boss Loot

### ISSUE THREAD

**Issue by Hype365** [thommcgrath/Beacon#75]
Any chance of getting the proper Ragnarok bosses added as well as maybe the Ragnarok mini-bosses? Currently all the existing bosses show as available on Ragnarok as well which is inaccurate as Ragnarok has it's own variation of the Dragon and Manticore only.

**Comment by thommcgrath** [comment]
If you have crate codes, I’d be happy to. It’s my understanding that what Beacon does right now is correct, so if I’m wrong, I’ll need to know the right information.

**Comment by Hype365** [comment]
Did some digging and testing and got the info you'll need to update the bosses list. Ragnarok bosses (Dragon and Manticore) use the same DinoDropInventoryComponent as the ones on Island and SE but I will list the full boss list with correct maps anyway.

Broodmother
Broodmother
Broodmother

**Comment by Hype365** [comment]
Did some digging and testing and got the info you'll need to update the bosses list. Ragnarok bosses appear to use the same DinoDropInventoryComponent as the ones on Island and SE (I had assumed they would be different but was mistaken, my apologies) but I will list the full boss list with correct maps and components anyway as what maps they are on is currently a little off.

**Main Bosses**
Broodmother Easy | The Island | DinoDropInventoryComponent_BossSpider_Easy_C
Broodmother Medium | The Island | DinoDropInventoryComponent_BossSpider_Medium_C
Broodmother Hard | The Island | DinoDropInventoryComponent_BossSpider_Hard_C

Broodmother Easy | The Center | DinoDropInventoryComponent_BossSpider_TheCenter_C
Broodmother Medium | The Center | DinoDropInventoryComponent_BossSpider_TheCenter_Medium_C
Broodmother Hard | The Center | DinoDropInventoryComponent_BossSpider_TheCenter_Hard_C

Megapithecus Easy | The Island | DinoDropInventoryComponent_BossGorilla_Easy_C
Megapithecus Medium | The Island | DinoDropInventoryComponent_BossGorilla_Medium_C
Megapithecus Hard | The Island | DinoDropInventoryComponent_BossGorilla_Hard_C

Megapithecus Easy | The Center | DinoDropInventoryComponent_BossGorilla_TheCenter_C
Megapithecus Medium | The Center | DinoDropInventoryComponent_BossGorilla_TheCenter_Medium_C
Megapithecus Hard | The Center | DinoDropInventoryComponent_BossGorilla_TheCenter_Hard_C

Dragon Easy | The Island & Ragnarok | DinoDropInventoryComponent_BossDragon_Easy_C
Dragon Medium | The Island & Ragnarok | DinoDropInventoryComponent_BossDragon_Medium_C
Dragon Hard | The Island & Ragnarok | DinoDropInventoryComponent_BossDragon_Hard_C

Manticore Easy | Scorched Earth & Ragnarok | DinoDropInventoryComponent_BossManticore_Easy_C
Manticore Medium | Scorched Earth & Ragnarok | DinoDropInventoryComponent_BossManticore_Medium_C
Manticore Hard | Scorched Earth & Ragnarok | DinoDropInventoryComponent_BossManticore_Hard_C

**Ragnarok Mini-Bosses**
Lava Golem | Ragnarok | DinoDropInventoryComponent_LavaGolem_jackson_C
Iceworm Queen | Ragnarok | DinoDropInventoryComponent_Carnivore_DeathwormAlpha_C (this is the same one as used by Alpha Deathworm so don't know if this should be included as it would mess with that one as well)

**Comment by thommcgrath** [comment]
Thanks for this. I have updated the loot source definitions. You should see the changes next time you launch Beacon.
