### ISSUE TITLE
Allow custom map with all loot sources

### ISSUE THREAD

**Issue by netopier7124** [thommcgrath/Beacon#77]
Dear developer,

I have my own custom map. I would like to create config for loots by your program, but currently I'm unable to do that, because I cant add all lootsources to any of currently offered map in your program. Could you please add "CustomMap" where all lootsources and items will be allowed?

Thank you.

Regards,
Alex.

**Comment by thommcgrath** [comment]
There are too many constraints to support this. Which ones do you need?

**Comment by netopier7124** [comment]
I have my own map, where I would like to use any drop/items. It would be nice to have "CustomMap" in pulldown menu when creating new document and choosing map. In this "CustomMap" every lootsource/item would be allowed.

**Comment by netopier7124** [comment]
It would be also good for admins which want to have same config for all servers and dont bother with differences. For example my 6 public servers, now I have to create separate config for Island/Abberation/TheCenter etc. If I could create CustomMap config where all lootcrates and items would be allowed, I would just copy paste same ini to all my servers/nodes. There will be no error because you can define abberation drop on Island map. Its just not used...

**Comment by thommcgrath** [comment]
It’s not about errors, it’s about logic. But good news, cluster support is already inbound, which will do what you need. You’ll be able to select multiple maps, so you could effectively just select all 5.

**Comment by netopier7124** [comment]
Very nice, thank you :)

**Comment by netopier7124** [comment]
Anyway about logic, I understand...but many players dont have access to datadisks but they want have access to new dinos and items on old maps. And also you have scorched items/dinos on Ragnarok but not on Island? Currently there are ways how to spawn datadisk dinos on normal maps and also you can put items into loot crates. Therefore there should be option to disable this limitation :) On my servers all items are present on all drops... I dont understand why should I not add scorched items to Island map, when they already are in ragnarok. Island players would have handicap...

**Comment by thommcgrath** [comment]
You can absolutely add items from any dlc or mod to any loot source. The map selection determines quality multiplier and how *presets* react to loot sources. I have SE items in my Aberration drops, for example.

**Comment by netopier7124** [comment]
Then my problem will be solved with that cluster option. Thank you so much for your work and support :)

**Comment by thommcgrath** [comment]
This feature has been implemented by 2a5b3845445129a071786cbdec214f92f2fac393 and will be included in the next build.
