### ISSUE TITLE
settings reverting back to default when deploying new drop settings

### ISSUE THREAD

**Issue by Angryman565** [thommcgrath/Beacon#79]
Used the program to mod drops and now when logging back on the drops are fine but other settiings revert back to default(weight, fortitude, crafting, collision, etc).  How can i fix this?

**Comment by thommcgrath** [comment]
It sounds like you’re replacing your entire Game.ini with the one Beacon creates. I recommend downloading your current Game.ini, and when you export from Beacon, choose to update it. Then upload that to your server.
