### ISSUE TITLE
Preset Editing Overhaul

### ISSUE THREAD

**Issue by thommcgrath** [thommcgrath/Beacon#8]
Preset editing is pretty clumsy right now. The big issue is item management. Adding items to a preset means adding a preset to a loot source, but the very nature of presets means the items added won't be the same as what was saved.

Presets also need added granularity for multipliers. The current quantity multipliers work for the items in each set entry. Which is a fine feature, but we need entry count multipliers too.

**Comment by tommy290** [comment]
It would be helpful if you could delete presets too (or if you can, make it more obvious how because I couldn't figure it out).

**Comment by thommcgrath** [comment]
To edit a preset right now, hold option/alt while selecting a preset from the menu. In the edit window, there will be a delete button in the bottom left if the preset is fully custom or an edited built-in preset.

This is part of why I want to completely overhaul how presets are edited. Nearly nothing about preset management feels right. I'm really not happy with how the feature turned out.

**Comment by thommcgrath** [comment]
Just commenting for my own record keeping before bed. There will be a preset library where your presets reside for editing, export, etc.

So each preset exists in one of three states: built-in, custom, and customized built-in. You'll be able to delete custom presets, and revert customized built-in presets. Built-in cannot be deleted.

**Comment by thommcgrath** [comment]
Next build will be much nicer. New preset features and a library window to manage them.
