### ISSUE TITLE
Quality reset help!!!!

### ISSUE THREAD

**Issue by UnderworldArk** [thommcgrath/Beacon#82]
following the newest TLC update for Ark Survival Evolved all of the qualities set in Beacon have been reset to 0.  Is there a way to recover all of my previous work?

**Comment by thommcgrath** [comment]
Ark updating will have no effect on your settings. Did you perhaps try to import your Game.ini back into Beacon? Don’t do that, Beacon adjusts values on export, but has no way to reverse that work on import. It wasn’t design for a back-and-forth usage.

Hopefully you saved your Beacon document so you can simply open that, make any adjustments you need, then export again. If you didn’t, there’s not much I can recommend.
