### ISSUE TITLE
Crash when attempting to browse library

### ISSUE THREAD

**Issue by InkDragon** [thommcgrath/Beacon#84]
Like the title says, I crash when attempting to load in the library after either changing the tab then going back to Documents or selecting an option from the dropdown.
Error Message is: 
"An exception of class Xojo.Core.UnsupportedOperationException was not handled. The application must shut down."

**Comment by thommcgrath** [comment]
Try going to the About window (from the Help menu) and clicking "Update Engrams" - if it tells you you're up to date, then this will take some more investigation. However, if it produces an error too, then you need to install https://support.microsoft.com/en-gb/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in - let me know how it goes and we'll try to figure it out from there.

**Comment by InkDragon** [comment]
Update worked fine, everything seems to work fine now, seems like the first few times the list wasn't loading fast enough(it was empty) and that's what caused the issue. Works fine now. Thank you for the help, sorry for any trouble
