### ISSUE TITLE
Ragnarok drops not working.

### ISSUE THREAD

**Issue by Garrettkv1** [thommcgrath/Beacon#87]
I've got the center drops working flawlessly. I made a new file under the ragnarok map. Copy and pasted all the file entrys from my center map. Then repeated them on the scorched drops and none of them work. Then i tried applying them from scratch with the ragnarok map. And nothing i do works ive spent 20 hours roughly trying to resolve the issue and i can't seem to figure it out. Please help :(.

**Comment by thommcgrath** [comment]
Sorry about the delay. Usually when I hear about partially working configurations, the solution is to enable expert mode on Nitrado. All this content needs to go into the Game.ini file, **NOT** the engine settings that some guides suggest. There is a limit to the amount of content that can be put there, and was never intended for game config options anyway.
