### ISSUE TITLE
Import from .ini does not import quality

### ISSUE THREAD

**Issue by timoage** [thommcgrath/Beacon#88]
I exported a game.ini from Beacon and instantly reimported it with the function to load from .ini file. Its all imported, but the quality of all items is set to primitive.

This is the source.ini
![grafik](https://user-images.githubusercontent.com/20972694/39154588-18213b88-474f-11e8-9f6d-6f08741e7c9d.png)

![grafik](https://user-images.githubusercontent.com/20972694/39154617-30513550-474f-11e8-9354-fef83a34a6da.png)

[asd.ini.txt](https://github.com/thommcgrath/Beacon/files/1940125/asd.ini.txt)

**Comment by thommcgrath** [comment]
Don't do that. The code that Beacon exports is multiplied by loot source qualities to ensure you get what you intended. However, importing must take the values as they are. You should not import code that was generated by Beacon.

**Comment by timoage** [comment]
okay, maybe make a hint when importing for idiots like me :tongue:
