### ISSUE TITLE
wont open library

### ISSUE THREAD

**Issue by thevandexiam** [thommcgrath/Beacon#89]
library wont open and i have drops that are standard even though they are coded to have more loot

**Comment by thommcgrath** [comment]
For the library not opening, I’m going to need more details.

For the loot not appearing as edited, take a look at https://beaconapp.cc/read.php/775966c2-b58a-417f-86f8-fd31644a1e09

**Comment by thevandexiam** [comment]
I click library and it opens the tab but doesn't load anything
