### ISSUE TITLE
Tek Railgun

### ISSUE THREAD

**Issue by OrdainedShamgar** [thommcgrath/Beacon#97]
I was putting the railgun in a beacon and when I tested it on the server it was a tek railing

**Comment by thommcgrath** [comment]
Are you sure you chose the railgun and not the railing? The Tek Railgun is called "TekSniper" in code, as seen at https://beaconapp.cc/object.php/d35d97ff-1f4b-4925-9956-61a61ae607e8 so I have a hard time believing the code made the mistake.

**Comment by OrdainedShamgar** [comment]
That is what I thought at first so I checked beacon again and made sure I had it in as the Railgun.  Deployed and checked the .ini and it had the tekrailing intead of tek sniper.  I changed manually.  Just wanted to let you know about it.  Beacon has been a life saver

**Comment by thommcgrath** [comment]
Can you attach a document that shows this happening? I just tried it here, and the code definitely includes the correct class string:

```
ConfigOverrideSupplyCrateItems=(SupplyCrateClassString="SupplyCrate_Level03_C",MinItemSets=1,MaxItemSets=1,NumItemSetsPower=1,bSetsRandomWithoutReplacement=true,ItemSets=((SetName="Untitled Item Set",MinNumItems=1,MaxNumItems=1,NumItemsPower=1,SetWeight=1000,bItemsRandomWithoutReplacement=true,ItemEntries=((EntryWeight=1000,ItemClassStrings=("PrimalItem_TekSniper_C"),ItemsWeights=(1000),MinQuantity=1,MaxQuantity=1,MinQuality=0,MaxQuality=0,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.25)))))
```

**Comment by OrdainedShamgar** [comment]
I can not get it to duplicate.  It was most likley user error.  Sorry about wating your time and again thank you.  You have saved me hours of work.

**Comment by thommcgrath** [comment]
No need to apologize, thanks for the update.
